# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b83f15af20cba3bf35c0dbb0d3c6e667b345917c9836e0306a038501e382da35ac0a2e2465c440bdfc57ed811785f80fe6fba696f8c6df977e05afddbecff8b

test:
  secret_key_base: c719082c5a5986ef641858efb115503600727bb783928cd6dcf1e0ba82265f69dc855de0e97728dc1564439efa4612927f196168e21578fb191a9053c3a0ccb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
